#!/usr/bin/env bash
set -euo pipefail

log() { printf '[%(%Y-%m-%dT%H:%M:%S%z)T] [fix-nginx-proxy] %s\n' -1 "$*"; }
warn() { printf '[%(%Y-%m-%dT%H:%M:%S%z)T] [fix-nginx-proxy][WARN] %s\n' -1 "$*" >&2; }
abort() { printf '[%(%Y-%m-%dT%H:%M:%S%z)T] [fix-nginx-proxy][ERROR] %s\n' -1 "$*" >&2; exit 1; }

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  abort "Bitte als root bzw. mit sudo ausführen."
fi

BACKEND_HOST="${BACKEND_HOST:-192.168.178.157}"
BACKEND_PORT="${BACKEND_PORT:-8000}"
BACKEND_SCHEME="${BACKEND_SCHEME:-http}"

log "Nginx-Proxy-Konfiguration wird repariert..."
log "  Backend: $BACKEND_SCHEME://$BACKEND_HOST:$BACKEND_PORT"

# Rate-Limiting-Konfiguration
log "Rate-Limiting-Konfiguration erstellen..."
cat >/etc/nginx/conf.d/tick-guard-rate-limit.conf <<'EOF'
limit_req_zone $binary_remote_addr zone=tick_guard_api:10m rate=10r/s;
EOF

# Common Snippet aktualisieren
COMMON_SNIPPET=/etc/nginx/snippets/tick-guard-common.conf
log "Common Snippet aktualisieren: $COMMON_SNIPPET"

cat >"$COMMON_SNIPPET" <<EOF
# Auto-generated by fix_nginx_proxy.sh
# Do not edit manually - wird bei jedem Update überschrieben

location /api/ {
    proxy_pass $BACKEND_SCHEME://$BACKEND_HOST:$BACKEND_PORT/api/;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;
    
    # Timeouts für längere Requests
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    
    # Rate Limiting
    limit_req zone=tick_guard_api burst=20 nodelay;
    
    # Error Handling
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
    proxy_next_upstream_tries 2;
    proxy_next_upstream_timeout 10s;
}

location /health {
    proxy_pass $BACKEND_SCHEME://$BACKEND_HOST:$BACKEND_PORT/health;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-Proto \$scheme;
    access_log off;
}

location / {
    try_files \$uri /index.html;
}

location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
    default_type "text/plain";
}
EOF

log "✅ Common Snippet aktualisiert"

# Prüfe ob Nginx-Site existiert
NGINX_SITE=/etc/nginx/sites-available/tick-guard
if [[ ! -f "$NGINX_SITE" ]]; then
  warn "Nginx-Site $NGINX_SITE nicht gefunden - erstelle Standard-Konfiguration..."
  
  PUBLIC_HOST="${PUBLIC_HOST:-$(hostname -I | awk '{print $1}')}"
  
  cat >"$NGINX_SITE" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $PUBLIC_HOST;

    include snippets/tick-guard-common.conf;
}
EOF
  
  log "Standard-HTTP-Server erstellt"
fi

# Site aktivieren
if [[ ! -L /etc/nginx/sites-enabled/tick-guard ]]; then
  log "Nginx-Site aktivieren..."
  ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/tick-guard
fi

# Nginx-Konfiguration testen
log "Nginx-Konfiguration testen..."
if nginx -t 2>&1; then
  log "✅ Nginx-Konfiguration ist gültig"
  
  # Nginx neu laden
  log "Nginx neu laden..."
  if systemctl reload nginx; then
    log "✅ Nginx erfolgreich neu geladen"
  else
    warn "⚠️  Nginx konnte nicht neu geladen werden - versuche restart..."
    systemctl restart nginx || abort "Nginx konnte nicht gestartet werden"
  fi
else
  abort "Nginx-Konfiguration ist ungültig - bitte manuell prüfen"
fi

# Backend-Verbindung testen
log "Backend-Verbindung testen..."
if command -v curl >/dev/null 2>&1; then
  BACKEND_URL="$BACKEND_SCHEME://$BACKEND_HOST:$BACKEND_PORT/health"
  log "Teste: $BACKEND_URL"
  
  if curl -sSf --max-time 5 "$BACKEND_URL" >/dev/null 2>&1; then
    log "✅ Backend ist erreichbar"
  else
    warn "⚠️  Backend ist NICHT erreichbar unter $BACKEND_URL"
    warn "   Bitte prüfen:"
    warn "   - Läuft das Backend? (systemctl status tick-guard-backend)"
    warn "   - Ist die IP korrekt? ($BACKEND_HOST)"
    warn "   - Ist der Port korrekt? ($BACKEND_PORT)"
    warn "   - Gibt es Firewall-Regeln?"
  fi
else
  warn "curl nicht verfügbar - Backend-Verbindungstest übersprungen"
fi

cat <<SUMMARY

✅ Nginx-Proxy-Konfiguration wurde aktualisiert!

Konfiguration:
  Backend: $BACKEND_SCHEME://$BACKEND_HOST:$BACKEND_PORT
  Common Snippet: $COMMON_SNIPPET
  Nginx-Site: $NGINX_SITE

Nächste Schritte:
  1. Prüfe Backend-Status: systemctl status tick-guard-backend (auf Backend-CT)
  2. Teste Backend direkt: curl http://$BACKEND_HOST:$BACKEND_PORT/health
  3. Prüfe Nginx-Logs: tail -f /var/log/nginx/error.log
  4. Teste Frontend: http://$(hostname -I | awk '{print $1}')/

Bei Problemen:
  - Nginx-Logs: tail -f /var/log/nginx/error.log /var/log/nginx/access.log
  - Backend-Logs: journalctl -u tick-guard-backend -n 50 (auf Backend-CT)
  - Nginx-Konfiguration prüfen: nginx -t

SUMMARY

